### ISSUE TITLE
MajorityLeader lack of config naming consistency

### ISSUE THREAD

**Issue by speedcom** [TanUkkii007/akka-cluster-custom-downing#11]
We have there:
`custom-downing.majority-auto-downing` and `custom-downing.majority-leader-auto-downing`.
Shouldn't this be the same? I think we should stick to one naming.

Under `reference.conf` file there is defined section for `majority-auto-downing` but here https://github.com/TanUkkii007/akka-cluster-custom-downing/blob/master/src/main/scala/tanukki/akka/cluster/autodown/MajorityLeaderAutoDowning.scala we read `down-if-in-minority` and `shutdown-actor-system-on-resolution` from `majority-leader-auto-downing`. 

It's clearly inconsistent.

**Comment by TanUkkii007** [comment]
fixed in version 0.0.9
