### ISSUE TITLE
Invalid artifact groupId

### ISSUE THREAD

**Issue by coudy** [TanUkkii007/akka-cluster-custom-downing#3]
Maven `groupId`s must not contain slashes, so using this from Maven/Java as currently hosted on Bintray requires some hacking. `github.com/TanUkkii007` should ideally be changed to `com.github.TanUkkii007`.

**Comment by TanUkkii007** [comment]
Thanks for letting me know.
I confirmed Maven naming conventions.  
https://maven.apache.org/guides/mini/guide-naming-conventions.html
I will fix as you suggested.
