### ISSUE TITLE
Scala 2.12 artifact

### ISSUE THREAD

**Issue by coudy** [TanUkkii007/akka-cluster-custom-downing#4]
Now that Scala 2.12 is out it'd be nice to have a compatible published artifact.

**Comment by TanUkkii007** [comment]
As far as I know, Akka is not published for >= Scala 2.12.0 yet.
Once it is released, I will prepare for 2.12 build.

**Comment by coudy** [comment]
It is actually. http://search.maven.org/#artifactdetails%7Ccom.typesafe.akka%7Cakka-actor_2.12%7C2.4.12%7Cjar

**Comment by TanUkkii007** [comment]
Oh really.
So now it is the time.

**Comment by TanUkkii007** [comment]
Now version 0.0.7 is available for Scala 2.11 and 2.12.
This is my Scala 2.12 debut.
