### ISSUE TITLE
unable to parse configuration

### ISSUE THREAD

**Issue by fflatorre** [TanUkkii007/akka-cluster-custom-downing#7]
Hi,

Just started to play around this very promising library, and following the instructions available here :
https://github.com/TanUkkii007/akka-cluster-custom-downing

I've setup my little akka app as follow :

```
akka {

    custom-downing {
       stable-after = 20s
       quorum-leader-auto-downing {
         role = ""
         quorum-size = 0
         down-if-out-of-quorum = true
       }
    }

    remote {
        netty.tcp {
              [... other stuff ...]
        }
    }
	
    cluster {
        downing-provider-class = "tanukki.akka.cluster.autodown.QuorumLeaderAutoDowning"
        
        [... other stuff ...]
    }

}
```

But got the following exception :

> 02/15-18:13:22<17794> Uncaught error from thread [activity-feeds-akka.actor.default-dispatcher-4] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[activity-feeds]
> 02/15-18:13:22<17794> java.lang.NoSuchMethodError: com.typesafe.config.Config.getDuration(Ljava/lang/String;)Ljava/time/Duration;
> 02/15-18:13:22<17794> at tanukki.akka.cluster.autodown.QuorumLeaderAutoDowning.downingActorProps(QuorumLeaderAutoDowning.scala:16)
> 02/15-18:13:22<17794> at akka.cluster.ClusterCoreDaemon.preStart(ClusterDaemon.scala:303)
> 02/15-18:13:22<17794> at akka.actor.Actor$class.aroundPreStart(Actor.scala:504)
> 02/15-18:13:22<17794> at akka.cluster.ClusterCoreDaemon.aroundPreStart(ClusterDaemon.scala:241)
> 02/15-18:13:22<17794> at akka.actor.ActorCell.create(ActorCell.scala:590)
> 02/15-18:13:22<17794> at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
> 02/15-18:13:22<17794> at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
> 02/15-18:13:22<17794> at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
> 02/15-18:13:22<17794> at akka.dispatch.Mailbox.run(Mailbox.scala:223)
> 02/15-18:13:23<17794> at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
> 02/15-18:13:23<17794> at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
> 02/15-18:13:23<17794> at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
> 02/15-18:13:23<17794> at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
> 02/15-18:13:23<17794> at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

I'm using :

```
            <dependency>
                <groupId>com.github.TanUkkii007</groupId>
                <artifactId>akka-cluster-custom-downing_2.11</artifactId>
                <version>0.0.7</version>
            </dependency>
```

and this is what's part of my classpath in terms of "akka-related" libs :

> akka-actor_2.11-2.4.16.jar
> akka-cluster_2.11-2.4.16.jar
> akka-cluster-custom-downing_2.11-0.0.7.jar
> akka-cluster-tools_2.11-2.4.16.jar
> akka-contrib_2.11-2.4.16.jar
> akka-persistence_2.11-2.4.16.jar
> akka-protobuf_2.11-2.4.16.jar
> akka-remote_2.11-2.4.16.jar
> akka-slf4j_2.11-2.4.16.jar
> akka-stream_2.11-2.4.16.jar
> akka-stream-experimental_2.11-1.0-RC4.jar
> ssl-config-akka_2.11-0.2.1.jar

Any clue on why I'm not able to parse the "stable-afer" setting ?

Cheers,
Francesco

**Comment by dr3s** [comment]
You have too many and different versions of akka. Use dependency management in maven.

**Comment by fflatorre** [comment]
I should have been more clear : only the jars related to version 2.4.16 are included in the classpath. That's what the common libs directory looks like. I'll edit the comment accordingly for a better understanding. Cheers, F

**Comment by TanUkkii007** [comment]
@fflatorre Thanks for reporting!
Since it shows `java.lang.NoSuchMethodError`, I think the problem is related to jar conflicts.
Akka is binary compatible within minor versions except for experimental modules.
I doubt akka-stream-experimental_2.11-1.0-RC4.jar, which is experimental and old version of akka-stream. Removing akka-stream-experimental from dependency may solve your problem.

**Comment by fflatorre** [comment]
Hi @dr3s ,

Thanks for the message. Apologies for the confusion, I reported the libs by visual inspection and I've just realised the list was (still) not correct. That's the definite akka dependencies : 

```
../lib/akka-protobuf_2.11-2.4.16.jar:
../lib/akka-cluster-custom-downing_2.11-0.0.7.jar
../lib/akka-persistence_2.11-2.4.16.jar
../lib/akka-stream_2.11-2.4.16.jar
../lib/akka-cluster_2.11-2.4.16.jar
../lib/akka-actor_2.11-2.4.16.jar:
../lib/akka-cluster-tools_2.11-2.4.16.jar
../lib/akka-remote_2.11-2.4.16.jar
../lib/akka-contrib_2.11-2.4.16.jar
../lib/akka-slf4j_2.11-2.4.16.jar
```

And this is the ultimate complete list of libs in the classpath :

```
../lib/ifxjdbc-3.70.JC8W1.jar:
../lib/log4j-1.2.17.jar:
../lib/scala-library-2.11.8.jar:
../lib/ehcache-2.9.1.jar:
../lib/aopalliance-1.0.jar:
../lib/akka-protobuf_2.11-2.4.16.jar:
../lib/akka-cluster-custom-downing_2.11-0.0.7.jar:
../lib/commons-compiler-2.7.8.jar:
../lib/ssl-config-core_2.11-0.2.1.jar:
../lib/zkclient-0.9.jar:
../lib/spring-boot-autoconfigure-1.1.8.RELEASE.jar:
../lib/guava-17.0.jar:
../lib/akka-persistence_2.11-2.4.16.jar:
../lib/aeron-driver-1.0.4.jar:
../lib/spring-data-redis-1.6.0.RELEASE.jar:
../lib/protobuf-java-2.6.1.jar:
../lib/spring-jdbc-4.0.6.RELEASE.jar:
../lib/spring-boot-starter-1.1.8.RELEASE.jar:
../lib/zookeeper-3.4.8.jar:
../lib/logback-core-1.1.2.jar:
../lib/dblogging-0.9.8.jar:
../lib/netty-3.10.6.Final.jar:
../lib/uncommons-maths-1.2.2a.jar:
../lib/jcl-over-slf4j-1.7.7.jar:
../lib/akka-stream_2.11-2.4.16.jar:
../lib/logback-classic-1.1.2.jar:
../lib/lz4-1.3.0.jar:
../lib/akka-cluster_2.11-2.4.16.jar:
../lib/spring-expression-4.0.6.RELEASE.jar:
../lib/spring-boot-starter-logging-1.1.8.RELEASE.jar:
../lib/java-uuid-generator-3.1.3.jar:
../lib/scala-java8-compat_2.11-0.7.0.jar:
../lib/log4j-over-slf4j-1.7.7.jar:
../lib/activity-feeds-core-model-0.2.32-SNAPSHOT.jar:
../lib/akka-actor_2.11-2.4.16.jar:
../lib/akka-cluster-tools_2.11-2.4.16.jar:
../lib/spring-web-4.0.6.RELEASE.jar:
../lib/spring-aop-4.0.6.RELEASE.jar:
../lib/commons-collections-3.2.1.jar:
../lib/akka-remote_2.11-2.4.16.jar:
../lib/activity-feeds-common-0.2.49-SNAPSHOT.jar:
../lib/akka-contrib_2.11-2.4.16.jar:
../lib/commons-pool-1.6.jar:
../lib/metrics-core-2.2.0.jar:
../lib/protostuff-core-1.0.8.jar:
../lib/spring-boot-1.1.8.RELEASE.jar:
../lib/akka-slf4j_2.11-2.4.16.jar:
../lib/Agrona-0.9.0.jar:
../lib/scala-parser-combinators_2.11-1.0.4.jar:
../lib/janino-2.7.8.jar:
../lib/bonecp-0.8.0.RELEASE.jar:
../lib/spring-context-4.0.6.RELEASE.jar:
../lib/commons-cli-1.2.jar:
../lib/snappy-java-1.1.2.6.jar:
../lib/kafka_2.11-0.10.1.1.jar:
../lib/spring-context-support-4.0.6.RELEASE.jar:
../lib/config-1.2.1.jar:
../lib/activity-feeds-core-dao-0.2.49-SNAPSHOT.jar:
../lib/javax.inject-1.jar:
../lib/spring-beans-4.0.6.RELEASE.jar:
../lib/reactive-streams-1.0.0.jar:
../lib/kafka-clients-0.10.1.1.jar:
../lib/jopt-simple-4.9.jar:
../lib/protostuff-api-1.0.8.jar:
../lib/commons-logging-1.1.3.jar:
../lib/activity-feeds-composer-0.2.49-SNAPSHOT.jar:
../lib/spring-tx-4.0.6.RELEASE.jar:
../lib/jul-to-slf4j-1.7.7.jar:
../lib/aeron-client-1.0.4.jar:
../lib/snakeyaml-1.13.jar:
../lib/activity-feeds-collector-0.2.49-SNAPSHOT.jar:
../lib/spring-core-4.0.6.RELEASE.jar:
../lib/slf4j-api-1.7.7.jar
```

Any clue ?

Cheers,
Francesco

**Comment by dr3s** [comment]
You are most certainly dealing with compatibility between akka and config.  You are using config 1.2.1 but akka specifies 1.3.0 in its pom.

https://mvnrepository.com/artifact/com.typesafe.akka/akka-actor_2.11/2.4.16

**Comment by fflatorre** [comment]
Brilliant ! Great catch @dr3s ! Everything it's now starting fine. Won't test it on a Friday at 8PM. I might get back to you on Monday if need.
In the meantime thanks for your help, very much appreciated.

Cheers,
Francesco
